"""Reusable rank-frequency-curve utilities."""

from .fit_models import (
    DEFAULT_BOUNDED_MIN_FREQUENCY,
    compute_fit_statistics,
    compute_powerlaw_statistics,
    fit_exponential,
    fit_linear,
    fit_power_law,
    negative_log_likelihood,
)
from .plotting import (
    create_all_plots,
    create_dataset_plots,
    create_dataset_unfitted_plots,
    create_loglog_rfc_plot,
    create_loglog_subfigure_plot,
    normalize_for_plot,
)
from .rank_frequency_extraction import (
    extract_frequency_counts,
    extract_rank_frequencies,
    extract_rank_frequencies_from_counts,
    extract_rank_frequencies_from_event_log,
)
from .case_attribute_association import (
    associate_attribute_with_variant,
    entropy_reduction_metrics,
    shannon_entropy,
)
from .case_attribute_config import (
    SCHEMA_VERSION,
    build_inventory_row,
    build_powerlaw_selection_row,
    load_csv,
    merge_inventory_dataframe,
    merge_powerlaw_selection_dataframe,
    resolve_field,
    resolve_inventory_row,
    resolve_powerlaw_row,
    write_csv,
)
from .case_attribute_inventory import (
    AttributeInventory,
    DatatypeRecommendation,
    PowerlawIncludeRecommendation,
    RecommendationThresholds,
    describe_attribute,
    infer_attribute_type,
    recommend_datatype,
    recommend_powerlaw_discrete,
    recommend_powerlaw_include,
    values_are_integer_valued,
)
from .case_attribute_transform import (
    extract_continuous_values,
    transform_by_datatype,
    value_frequency_counts,
)
from .types import FitStatistics

__all__ = [
    "AttributeInventory",
    "DEFAULT_BOUNDED_MIN_FREQUENCY",
    "DatatypeRecommendation",
    "FitStatistics",
    "PowerlawIncludeRecommendation",
    "RecommendationThresholds",
    "SCHEMA_VERSION",
    "associate_attribute_with_variant",
    "build_inventory_row",
    "build_powerlaw_selection_row",
    "compute_fit_statistics",
    "compute_powerlaw_statistics",
    "create_all_plots",
    "create_dataset_plots",
    "create_dataset_unfitted_plots",
    "create_loglog_rfc_plot",
    "create_loglog_subfigure_plot",
    "describe_attribute",
    "entropy_reduction_metrics",
    "extract_continuous_values",
    "extract_frequency_counts",
    "extract_rank_frequencies",
    "extract_rank_frequencies_from_counts",
    "extract_rank_frequencies_from_event_log",
    "fit_exponential",
    "fit_linear",
    "fit_power_law",
    "infer_attribute_type",
    "load_csv",
    "merge_inventory_dataframe",
    "merge_powerlaw_selection_dataframe",
    "negative_log_likelihood",
    "normalize_for_plot",
    "recommend_datatype",
    "recommend_powerlaw_discrete",
    "recommend_powerlaw_include",
    "resolve_field",
    "resolve_inventory_row",
    "resolve_powerlaw_row",
    "shannon_entropy",
    "transform_by_datatype",
    "value_frequency_counts",
    "values_are_integer_valued",
    "write_csv",
]
